enum ERequestActions {
  CREATE_REQUEST_EQUIPMENT = "CREATE_REQUEST_EQUIPMENT",
  CREATE_REQUEST_EQUIPMENT_REQUEST = "CREATE_REQUEST_EQUIPMENT_REQUEST",
  CREATE_REQUEST_EQUIPMENT_SUCCESS = "CREATE_REQUEST_EQUIPMENT_SUCCESS",
  CREATE_REQUEST_EQUIPMENT_FAILURE = "CREATE_REQUEST_EQUIPMENT_FAILURE",

  GET_REQUEST_EQUIPMENT = "GET_REQUEST_EQUIPMENT",
  GET_REQUEST_EQUIPMENT_REQUEST = "GET_REQUEST_EQUIPMENT_REQUEST",
  GET_REQUEST_EQUIPMENT_SUCCESS = "GET_REQUEST_EQUIPMENT_SUCCESS",
  GET_REQUEST_EQUIPMENT_FAILURE = "GET_REQUEST_EQUIPMENT_FAILURE",
}

export { ERequestActions };
