enum EUserActions {
  GET_USERS = "GET_USERS",
  GET_USERS_REQUEST = "GET_USERS_REQUEST",
  GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
  GET_USERS_FAILURE = "GET_USERS_FAILURE",

  CREATE_USER = "CREATE_USER",
  CREATE_USER_REQUEST = "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE = "CREATE_USER_FAILURE",

  UPDATE_USER = "UPDATE_USER",
  UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE",

  DELETE_USER = "DELETE_USER",
  DELETE_USER_REQUEST = "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE = "DELETE_USER_FAILURE",

  TRANSFER_EQUIPMENT = "TRANSFER_EQUIPMENT",
  TRANSFER_EQUIPMENT_REQUEST = "TRANSFER_EQUIPMENT_REQUEST",
  TRANSFER_EQUIPMENT_SUCCESS = "TRANSFER_EQUIPMENT_SUCCESS",
  TRANSFER_EQUIPMENT_FAILURE = "TRANSFER_EQUIPMENT_FAILURE",
}

export { EUserActions };
