enum ENotificationActions {
  GET_NOTIFICATION = "GET_NOTIFICATION",
  GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST",
  GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS",
  GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE",

  READ_NOTIFICATION = "READ_NOTIFICATION",
  READ_NOTIFICATION_REQUEST = "READ_NOTIFICATION_REQUEST",
  READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS",
  READ_NOTIFICATION_FAILURE = "READ_NOTIFICATION_FAILURE",

  CLEAR_ALL_NOTIFICATION = "CLEAR_ALL_NOTIFICATION",
  CLEAR_ALL_NOTIFICATION_REQUEST = "CLEAR_ALL_NOTIFICATION_REQUEST",
  CLEAR_ALL_NOTIFICATION_SUCCESS = "CLEAR_ALL_NOTIFICATION_SUCCESS",
  CLEAR_ALL_NOTIFICATION_FAILURE = "CLEAR_ALL_NOTIFICATION_FAILURE",

  READ_ALL_NOTIFICATION = "READ_ALL_NOTIFICATION",
  READ_ALL_NOTIFICATION_REQUEST = "READ_ALL_NOTIFICATION_REQUEST",
  READ_ALL_NOTIFICATION_SUCCESS = "READ_ALL_NOTIFICATION_SUCCESS",
  READ_ALL_NOTIFICATION_FAILURE = "READ_ALL_NOTIFICATION_FAILURE",
}

export { ENotificationActions };
