enum EEquipmentActions {
  CREATE_EQUIPMENT = "CREATE_EQUIPMENT",
  CREATE_EQUIPMENT_REQUEST = "CREATE_EQUIPMENT_REQUEST",
  CREATE_EQUIPMENT_SUCCESS = "CREATE_EQUIPMENT_SUCCESS",
  CREATE_EQUIPMENT_FAILURE = "CREATE_EQUIPMENT_FAILURE",

  GET_EQUIPMENT = "GET_EQUIPMENT",
  GET_EQUIPMENT_REQUEST = "GET_EQUIPMENT_REQUEST",
  GET_EQUIPMENT_SUCCESS = "GET_EQUIPMENT_SUCCESS",
  GET_EQUIPMENT_FAILURE = "GET_EQUIPMENT_FAILURE",

  UPDATE_EQUIPMENT = "UPDATE_EQUIPMENT",
  UPDATE_EQUIPMENT_REQUEST = "UPDATE_EQUIPMENT_REQUEST",
  UPDATE_EQUIPMENT_SUCCESS = "UPDATE_EQUIPMENT_SUCCESS",
  UPDATE_EQUIPMENT_FAILURE = "UPDATE_EQUIPMENT_FAILURE",

  DELETE_EQUIPMENT = "DELETE_EQUIPMENT",
  DELETE_EQUIPMENT_REQUEST = "DELETE_EQUIPMENT_REQUEST",
  DELETE_EQUIPMENT_SUCCESS = "DELETE_EQUIPMENT_SUCCESS",
  DELETE_EQUIPMENT_FAILURE = "DELETE_EQUIPMENT_FAILURE",
}

export { EEquipmentActions };
